"""init

Revision ID: e341f9ed3620
Revises: 
Create Date: 2019-06-05 11:17:29.690368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e341f9ed3620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(sa.schema.CreateSequence(sa.schema.Sequence('diseases_seq')))
    op.execute(sa.schema.CreateSequence(sa.schema.Sequence('patients_seq')))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('diseases_seq')"), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('international_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_international_code'), 'diseases', ['international_code'], unique=False)
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('patients_seq')"), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('deceased', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_birthday'), 'patients', ['birthday'], unique=False)
    op.create_index(op.f('ix_patients_surname'), 'patients', ['surname'], unique=False)
    op.create_table('patients_diseases',
    sa.Column('patient_id', sa.BigInteger(), nullable=True),
    sa.Column('disease_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], )
    )
    op.create_index(op.f('ix_patients_diseases_disease_id'), 'patients_diseases', ['disease_id'], unique=False)
    op.create_index(op.f('ix_patients_diseases_patient_id'), 'patients_diseases', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_diseases_patient_id'), table_name='patients_diseases')
    op.drop_index(op.f('ix_patients_diseases_disease_id'), table_name='patients_diseases')
    op.drop_table('patients_diseases')
    op.drop_index(op.f('ix_patients_surname'), table_name='patients')
    op.drop_index(op.f('ix_patients_birthday'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_international_code'), table_name='diseases')
    op.drop_table('diseases')
    # ### end Alembic commands ###

    op.drop_table('diseases_seq')
    op.drop_table('patients_seq')
